In [4]:
# Python ≥3.5 is required
import sys
assert sys.version_info >= (3, 5)

# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)

In [5]:
import pandas as pd
class StringConverter(dict):

    def __contains__(self, item):

        return True

    def __getitem__(self, item):

        return str

    def get(self, default=None):

        return str

def load_data(data_path = "/Users/vishali/Desktop/SPRING 2021/project-ml"):
    csv_path = os.path.join(data_path, "ch_imputed.csv")
    return pd.read_csv(csv_path, low_memory = False)

In [40]:
ch = load_data()

In [41]:
ch.info()

Unnamed: 0             X          sd1        hv204        hv206  \
count  9395.000000   9395.000000  9395.000000  9395.000000  9395.000000   
mean   4698.000000  22262.091964     0.482278   128.520809     0.219372   
std    2712.247223  12738.764883     0.499712   286.127055     0.413843   
min       1.000000      1.000000     0.000000     2.000000     0.000000   
25%    2349.500000  11275.500000     0.000000    15.000000     0.000000   
50%    4698.000000  22154.000000     0.000000    30.000000     0.000000   
75%    7046.500000  32813.000000     1.000000    60.000000     0.000000   
max    9395.000000  44985.000000     1.000000   996.000000     1.000000   

             hv207        hv208        hv209        hv210        hv211  ...  \
count  9395.000000  9395.000000  9395.000000  9395.000000  9395.000000  ...   
mean      0.531985     0.112826     0.017030     0.168175     0.019159  ...   
std       0.499002     0.316397     0.129391     0.374041     0.137091  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       1.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       1.000000     0.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

          PET_2015  Proximity_to_tiol_Borders  Proximity_to_Protected_Areas  \
count  9395.000000                9395.000000                   9395.000000   
mean      2.861483               23235.013448                  29222.281985   
std       0.188219               14578.638448                  18926.488291   
min       2.450000                 225.640000                      0.000000   
25%       2.690000               10497.340000                  12487.380000   
50%       2.890000               21882.130000                  26923.400000   
75%       3.000000               36685.810000                  45813.810000   
max       3.170000               55444.900000                  71428.820000   

       Proximity_to_Water  Rainfall_2015  Travel_Times_2015  \
count         9395.000000    9395.000000        9395.000000   
mean         22814.013185    1079.743748          38.247741   
std          13932.925922     219.290823          27.971789   
min              0.000000     740.600000           0.000000   
25%          11861.150000     872.000000          16.640000   
50%          22821.100000    1053.330000          35.330000   
75%          32177.580000    1243.900000          53.950000   
max          65493.430000    1621.000000         175.810000   

       UN_Population_Density_2015  Wet_Days_2015    washhands        smoke  
count                 9395.000000    9395.000000  9395.000000  9395.000000  
mean                  1003.719147      16.182889     0.108675     0.825652  
std                   1533.360813       0.627466     0.311247     0.379429  
min                    145.520000      15.180000     0.000000     0.000000  
25%                    458.850000      15.630000     0.000000     1.000000  
50%                    552.060000      16.390000     0.000000     1.000000  
75%                    738.380000      16.560000     0.000000     1.000000  
max                  10562.060000      17.310000     1.000000     1.000000  

[8 rows x 40 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9395 entries, 0 to 9394
Data columns (total 42 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Unnamed: 0                      9395 non-null   int64  
 1   X                               9395 non-null   int64  
 2   whsd                            9395 non-null   object 
 3   sd1                             9395 non-null   int64  
 4   hv204                           9395 non-null   int64  
 5   hv206                           9395 non-null   int64  
 6   hv207                           9395 non-null   int64  
 7   hv208                           9395 non-null   int64  
 8   hv209                           9395 non-null   int64  
 9   hv210                           9395 non-null   int64  
 10  hv211                           9395 non-null   int64  
 11  hv212                           9395 non-null   int64  
 12  hv216                           93

In [45]:
# drop object dtypes
del ch['whsd']
del ch['v025']

In [46]:
ch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9395 entries, 0 to 9394
Data columns (total 40 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Unnamed: 0                      9395 non-null   int64  
 1   X                               9395 non-null   int64  
 2   sd1                             9395 non-null   int64  
 3   hv204                           9395 non-null   int64  
 4   hv206                           9395 non-null   int64  
 5   hv207                           9395 non-null   int64  
 6   hv208                           9395 non-null   int64  
 7   hv209                           9395 non-null   int64  
 8   hv210                           9395 non-null   int64  
 9   hv211                           9395 non-null   int64  
 10  hv212                           9395 non-null   int64  
 11  hv216                           9395 non-null   int64  
 12  hv225                           93

In [48]:
X = ch.drop('sd1', axis=1)
y = ch['sd1']

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=1) 

In [51]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [52]:
y_pred = classifier.predict(X_test)

In [53]:
from sklearn.metrics import classification_report, confusion_matrix
CM = confusion_matrix(y_test, y_pred)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[888  89]
 [ 83 819]]
              precision    recall  f1-score   support

           0       0.91      0.91      0.91       977
           1       0.90      0.91      0.90       902

    accuracy                           0.91      1879
   macro avg       0.91      0.91      0.91      1879
weighted avg       0.91      0.91      0.91      1879



In [106]:
TN = CM[0][0]
FN = CM[1][0]
TP = CM[1][1]
FP = CM[0][1]

FNR = FN/(TP+FN)
FPR = FP/(FP+TN)
TPR = TP/(TP+FN)
print(FNR)
print(FPR)
print(TPR)

0.09201773835920177
0.09109518935516889
0.9079822616407982


In [138]:
from sklearn.metrics import roc_curve
from sklearn.metrics import auc

# Compute fpr, tpr, thresholds and roc auc
fpr, tpr, thresholds = roc_curve(y_pred, y_test)
roc_auc = auc(fpr, tpr)
roc_auc


0.4679020664869722

In [65]:
from sklearn import tree
from sklearn.model_selection import GridSearchCV
import random
from random import randint

In [143]:
max_depth_range = range(1,10)
min_samples_leaf_range = range(1,10)
parameters = {'criterion': ['gini'], 'max_depth': max_depth_range, 'min_samples_leaf': min_samples_leaf_range}
clf = GridSearchCV(tree.DecisionTreeClassifier(), parameters, n_jobs=4, cv= 5)
clf.fit(X=X, y=y)
tree_model = clf.best_estimator_
print (clf.best_score_, clf.best_params_) 

0.516338477913784 {'criterion': 'gini', 'max_depth': 1, 'min_samples_leaf': 1}


In [144]:
from sklearn.tree import DecisionTreeClassifier
classifier4 = DecisionTreeClassifier(max_depth = 1, min_samples_leaf = 1)
classifier4.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=1)

In [145]:
y_predA = classifier4.predict(X_val)

In [146]:
y_pred2 = classifier4.predict(X_test)

In [147]:
from sklearn.metrics import classification_report, confusion_matrix
CM2 = confusion_matrix(y_val, y_predA)
print(confusion_matrix(y_val, y_predA))
print(classification_report(y_val, y_pred))

[[979   6]
 [876  18]]
              precision    recall  f1-score   support

           0       0.53      0.99      0.69       985
           1       0.75      0.02      0.04       894

    accuracy                           0.53      1879
   macro avg       0.64      0.51      0.36      1879
weighted avg       0.63      0.53      0.38      1879



In [148]:
from sklearn.metrics import classification_report, confusion_matrix
CM2 = confusion_matrix(y_val, y_pred2)
print(confusion_matrix(y_val, y_pred2))
print(classification_report(y_val, y_pred))

[[975  10]
 [881  13]]
              precision    recall  f1-score   support

           0       0.53      0.99      0.69       985
           1       0.75      0.02      0.04       894

    accuracy                           0.53      1879
   macro avg       0.64      0.51      0.36      1879
weighted avg       0.63      0.53      0.38      1879



In [149]:
TN1 = CM2[0][0]
FN1 = CM2[1][0]
TP1 = CM2[1][1]
FP1 = CM2[0][1]

FNR1 = FN/(TP+FN)
FPR1 = FP/(FP+TN)
print(FNR1)
print(FPR1)

0.6465324384787472
0.05279187817258883


In [150]:
from sklearn.metrics import roc_curve
from sklearn.metrics import auc

# Compute fpr, tpr, thresholds and roc auc
fpr, tpr, thresholds = roc_curve(y_pred2, y_val)
roc_auc = auc(fpr, tpr)
roc_auc


0.5452703335832083

In [ ]:
# Part 2: Maternal Health

In [151]:
def load_data(data_path = "/Users/vishali/Desktop/SPRING 2021/project-ml"):
    csv_path = os.path.join(data_path, "mh_imputed.csv")
    return pd.read_csv(csv_path, low_memory = False)

In [152]:
mh = load_data()

In [153]:
X = mh.drop('anemia', axis=1)
y = mh['anemia']

In [154]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=1) 

In [155]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [156]:
y_pred = classifier.predict(X_test)

In [157]:
from sklearn.metrics import classification_report, confusion_matrix
CM = confusion_matrix(y_test, y_pred)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[3135  364]
 [ 374  530]]
              precision    recall  f1-score   support

           0       0.89      0.90      0.89      3499
           1       0.59      0.59      0.59       904

    accuracy                           0.83      4403
   macro avg       0.74      0.74      0.74      4403
weighted avg       0.83      0.83      0.83      4403



In [158]:
TN = CM[0][0]
FN = CM[1][0]
TP = CM[1][1]
FP = CM[0][1]

FNR = FN/(TP+FN)
FPR = FP/(FP+TN)
print(FNR)
print(FPR)

0.413716814159292
0.10402972277793655


In [159]:
from sklearn.metrics import roc_curve
from sklearn.metrics import auc

# Compute fpr, tpr, thresholds and roc auc
fpr, tpr, thresholds = roc_curve(y_pred, y_test)
roc_auc = auc(fpr, tpr)
roc_auc

0.7431290456053242

In [160]:
from sklearn import tree
from sklearn.model_selection import GridSearchCV
import random
from random import randint

In [161]:
max_depth_range = range(1,10)
min_samples_leaf_range = range(1,10)
parameters = [{'criterion': ['entropy', 'gini'], 'max_depth': max_depth_range},
              {'min_samples_leaf': min_samples_leaf_range}]
clf = GridSearchCV(tree.DecisionTreeClassifier(), parameters, cv = 5)
clf.fit(X=X, y=y)
tree_model = clf.best_estimator_
print (clf.best_score_, clf.best_params_) 

0.8004724794740028 {'criterion': 'entropy', 'max_depth': 1}


In [164]:
from sklearn.tree import DecisionTreeClassifier
classifier2 = DecisionTreeClassifier(max_depth = 1)
classifier2.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=1)

In [165]:
y_pred = classifier2.predict(X_val)

In [166]:
from sklearn.metrics import classification_report, confusion_matrix
CM2 = confusion_matrix(y_val, y_pred)
print(confusion_matrix(y_val, y_pred))
print(classification_report(y_val, y_pred))

[[3513    0]
 [ 890    0]]
              precision    recall  f1-score   support

           0       0.80      1.00      0.89      3513
           1       0.00      0.00      0.00       890

    accuracy                           0.80      4403
   macro avg       0.40      0.50      0.44      4403
weighted avg       0.64      0.80      0.71      4403



/Users/vishali/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [167]:
TN1 = CM2[0][0]
FN1 = CM2[1][0]
TP1 = CM2[1][1]
FP1 = CM2[0][1]

FNR1 = FN/(TP+FN)
FPR1 = FP/(FP+TN)
print(FNR1)
print(FPR1)

0.413716814159292
0.10402972277793655


In [169]:
from sklearn.metrics import roc_curve
from sklearn.metrics import auc

# Compute fpr, tpr, thresholds and roc auc
fpr, tpr, thresholds = roc_curve(y_pred, y_val)
roc_auc = auc(fpr, tpr)
roc_auc

/Users/vishali/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_ranking.py:811: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn("No positive samples in y_true, "


nan

In [170]:
# General Health
def load_data(data_path = "/Users/vishali/Desktop/SPRING 2021/project-ml"):
    csv_path = os.path.join(data_path, "gh_imputed.csv")
    return pd.read_csv(csv_path, low_memory = False)
gh = load_data()
gh.describe()

Unnamed: 0             X         v467c         hv204         hv206  \
count  44988.000000  44988.000000  44988.000000  44988.000000  44988.000000   
mean   22494.500000  22494.500000      0.517783    162.658620      0.268516   
std    12987.061292  12987.061292      0.499689    327.793449      0.443192   
min        1.000000      1.000000      0.000000      1.000000      0.000000   
25%    11247.750000  11247.750000      0.000000     15.000000      0.000000   
50%    22494.500000  22494.500000      1.000000     30.000000      0.000000   
75%    33741.250000  33741.250000      1.000000     60.000000      1.000000   
max    44988.000000  44988.000000      1.000000    998.000000      1.000000   

              hv207         hv208         hv209         hv210         hv211  \
count  44988.000000  44988.000000  44988.000000  44988.000000  44988.000000   
mean       0.580799      0.151396      0.029341      0.168556      0.022384   
std        0.493434      0.358438      0.168763      0.374363      0.147930   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        1.000000      0.000000      0.000000      0.000000      0.000000   
75%        1.000000      0.000000      0.000000      0.000000      0.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

       ...      PET_2015  Proximity_to_National_Borders  \
count  ...  44988.000000                   44988.000000   
mean   ...      2.857777                   23680.332020   
std    ...      0.183175                   14561.540236   
min    ...      2.450000                     225.643966   
25%    ...      2.691667                   10862.760050   
50%    ...      2.891667                   22674.780890   
75%    ...      3.000000                   37382.571370   
max    ...      3.166667                   55444.901540   

       Proximity_to_Protected_Areas  Proximity_to_Water  Rainfall_2015  \
count                  44988.000000        44988.000000   44988.000000   
mean                   29972.461377        23374.102287    1078.388691   
std                    19104.858188        13770.484973     216.128756   
min                        0.000000            0.000000     740.600000   
25%                    13068.324810        12557.675680     875.200000   
50%                    28938.692330        23393.676430    1051.400000   
75%                    46502.618000        32385.721920    1237.416667   
max                    71428.815020        65493.432620    1621.000000   

       Travel_Times_2015  UN_Population_Density_2015  Wet_Days_2015  \
count       44988.000000                44988.000000   44988.000000   
mean           37.404914                 1127.388953      16.212796   
std            28.398749                 1759.374216       0.619992   
min             0.000000                  145.523895      15.180833   
25%            15.357143                  458.852473      15.849167   
50%            34.498630                  553.622628      16.532499   
75%            53.297521                  748.146228      16.561666   
max           175.811475                10562.064580      17.305834   

              smoke     washhands  
count  44988.000000  44988.000000  
mean       0.819685      0.128123  
std        0.384454      0.334230  
min        0.000000      0.000000  
25%        1.000000      0.000000  
50%        1.000000      0.000000  
75%        1.000000      0.000000  
max        1.000000      1.000000  

[8 rows x 39 columns]

In [171]:
del gh['X']
X = gh.drop('v467c', axis=1)
y = gh['v467c']

In [172]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=1) 

In [175]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [177]:
y_pred = classifier.predict(X_test)

In [178]:
from sklearn.metrics import classification_report, confusion_matrix
CM = confusion_matrix(y_test, y_pred)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[3510  863]
 [ 831 3794]]
              precision    recall  f1-score   support

           0       0.81      0.80      0.81      4373
           1       0.81      0.82      0.82      4625

    accuracy                           0.81      8998
   macro avg       0.81      0.81      0.81      8998
weighted avg       0.81      0.81      0.81      8998



In [179]:
TN = CM[0][0]
FN = CM[1][0]
TP = CM[1][1]
FP = CM[0][1]

FNR = FN/(TP+FN)
FPR = FP/(FP+TN)
print(FNR)
print(FPR)

0.1796756756756757
0.1973473587925909


In [180]:
from sklearn.metrics import roc_curve
from sklearn.metrics import auc

# Compute fpr, tpr, thresholds and roc auc
fpr, tpr, thresholds = roc_curve(y_pred, y_test)
roc_auc = auc(fpr, tpr)
roc_auc

0.8116285105730663

In [181]:
from sklearn import tree
from sklearn.model_selection import GridSearchCV
import random
from random import randint

In [182]:
parameters = {"max_depth": range(1, 10)}
clf = GridSearchCV(tree.DecisionTreeClassifier(), parameters, n_jobs=4, cv= 5)
clf.fit(X=X, y=y)
tree_model = clf.best_estimator_
print (clf.best_score_, clf.best_params_) 

0.6285882604962069 {'max_depth': 3}


In [183]:
from sklearn.tree import DecisionTreeClassifier
classifier4 = DecisionTreeClassifier(max_depth = 3)
classifier4.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3)

In [184]:
y_predA = classifier4.predict(X_val)

In [185]:
from sklearn.metrics import classification_report, confusion_matrix
CM2 = confusion_matrix(y_val, y_predA)
print(confusion_matrix(y_val, y_predA))
print(classification_report(y_val, y_pred))

[[3030 1325]
 [1695 2948]]
              precision    recall  f1-score   support

           0       0.47      0.47      0.47      4355
           1       0.51      0.51      0.51      4643

    accuracy                           0.49      8998
   macro avg       0.49      0.49      0.49      8998
weighted avg       0.49      0.49      0.49      8998



In [186]:
TN1 = CM2[0][0]
FN1 = CM2[1][0]
TP1 = CM2[1][1]
FP1 = CM2[0][1]

FNR1 = FN/(TP+FN)
FPR1 = FP/(FP+TN)
print(FNR1)
print(FPR1)

0.1796756756756757
0.1973473587925909


In [187]:
from sklearn.metrics import roc_curve
from sklearn.metrics import auc

# Compute fpr, tpr, thresholds and roc auc
fpr, tpr, thresholds = roc_curve(y_predA, y_val)
roc_auc = auc(fpr, tpr)
roc_auc

0.6655916255260976